source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

target 'WebViewNode_Example' do
  pod 'WebViewNode', :subspecs => ['Web', 'JSBridge', 'Node'], :path => '../'

  target 'WebViewNode_Tests' do
    inherit! :search_paths

    #FIXME: Supports for Swift 4.2
    pod 'Quick'
    pod 'Nimble'
#    pod 'FBSnapshotTestCase'
#    pod 'Nimble-Snapshots'
  end
end
